const ACTIONS = {
  COVID_CASES_FETCH_INIT: 'COVID_CASES_FETCH_INIT',
  COVID_CASES_FETCH_SUCCESS: 'COVID_CASES_FETCH_SUCCESS',
  COVID_CASES_FETCH_FAIL: 'COVID_CASES_FETCH_FAIL',
  COVID_CASES_INVALIDATE: 'COVID_CASES_INVALIDATE',
};

export default ACTIONS;
